"""add employee_id to chat_messages

Revision ID: cf52763a8c4d
Revises: 2026_add_ml_task_id
Create Date: 2026-04-20 12:04:58.618332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf52763a8c4d'
down_revision: Union[str, Sequence[str], None] = '2026_add_ml_task_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_annotations_part_start_end_employee'), 'Annotations', type_='unique')
    op.add_column('ChatMessages', sa.Column('employee_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_ChatMessages_employee_id'), 'ChatMessages', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'ChatMessages', 'Staff', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_PartsTranscription_transcript_id'), 'PartsTranscription', ['transcript_id'], unique=False)
    op.drop_index(op.f('ix_transcripts_employee_id'), table_name='Transcripts')
    op.create_index(op.f('ix_Transcripts_employee_id'), 'Transcripts', ['employee_id'], unique=False)
    op.alter_column('scheduled_meetings', 'meeting_bot_task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID задачи Celery для meeting-bot (join)',
               existing_comment='ID задачи Celery для meeting-bot',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_meetings', 'meeting_bot_task_id',
               existing_type=sa.VARCHAR(length=100),
               comment='ID задачи Celery для meeting-bot',
               existing_comment='ID задачи Celery для meeting-bot (join)',
               existing_nullable=True)
    op.drop_index(op.f('ix_Transcripts_employee_id'), table_name='Transcripts')
    op.create_index(op.f('ix_transcripts_employee_id'), 'Transcripts', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_PartsTranscription_transcript_id'), table_name='PartsTranscription')
    op.drop_constraint(None, 'ChatMessages', type_='foreignkey')
    op.drop_index(op.f('ix_ChatMessages_employee_id'), table_name='ChatMessages')
    op.drop_column('ChatMessages', 'employee_id')
    op.create_unique_constraint(op.f('uq_annotations_part_start_end_employee'), 'Annotations', ['part_id', 'start_char', 'end_char', 'employee_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
