"""add_avatar_key_to_staff

Revision ID: de1c6a0a98e7
Revises: e40bd4fd5f6b
Create Date: 2026-05-21 08:00:28.821568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1c6a0a98e7'
down_revision: Union[str, Sequence[str], None] = 'e40bd4fd5f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Staff', sa.Column('avatar_key', sa.String(length=255), nullable=True, comment='Ключ объекта в MinIO (avatars/{user_id})'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Staff', 'avatar_key')
    # ### end Alembic commands ###
