"""added TranscriptsAccess model

Revision ID: f465f1ce55d8
Revises: cf52763a8c4d
Create Date: 2026-04-20 12:30:35.532827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f465f1ce55d8'
down_revision: Union[str, Sequence[str], None] = 'cf52763a8c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranscriptAccess',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['Transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TranscriptAccess_employee_id'), 'TranscriptAccess', ['employee_id'], unique=False)
    op.create_index(op.f('ix_TranscriptAccess_id'), 'TranscriptAccess', ['id'], unique=False)
    op.create_index(op.f('ix_TranscriptAccess_transcript_id'), 'TranscriptAccess', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TranscriptAccess_transcript_id'), table_name='TranscriptAccess')
    op.drop_index(op.f('ix_TranscriptAccess_id'), table_name='TranscriptAccess')
    op.drop_index(op.f('ix_TranscriptAccess_employee_id'), table_name='TranscriptAccess')
    op.drop_table('TranscriptAccess')
    # ### end Alembic commands ###
