"""move_ownership_to_access_table

Revision ID: e40bd4fd5f6b
Revises: f465f1ce55d8
Create Date: 2026-04-20 13:36:42.436350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40bd4fd5f6b'
down_revision: Union[str, Sequence[str], None] = 'f465f1ce55d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавляем колонку role в таблицу доступа (если её ещё нет)
    op.add_column('TranscriptAccess', sa.Column('role', sa.String(length=20), nullable=False, server_default='shared', comment='owner, shared'))

    # Убеждаемся, что расширение pgcrypto установлено для генерации UUID
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')

    # 2. Переносим данные о владельцах из таблицы Transcripts в TranscriptAccess
    # Это критически важный шаг, чтобы не потерять информацию о том, кто создал запись
    op.execute(
        'INSERT INTO "TranscriptAccess" (id, transcript_id, employee_id, role, granted_at) '
        'SELECT gen_random_uuid(), id, employee_id, \'owner\', created_at FROM "Transcripts"'
    )

    # 3. Теперь, когда данные сохранены, можно безопасно удалять старую колонку
    op.drop_index(op.f('ix_Transcripts_employee_id'), table_name='Transcripts')
    op.drop_constraint(op.f('fk_transcripts_employee_id'), 'Transcripts', type_='foreignkey')
    op.drop_column('Transcripts', 'employee_id')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transcripts', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_transcripts_employee_id'), 'Transcripts', 'Staff', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_Transcripts_employee_id'), 'Transcripts', ['employee_id'], unique=False)
    op.drop_column('TranscriptAccess', 'role')
    # ### end Alembic commands ###
