version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - meeting-network

  api:
    build: ./backend/api
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - meeting-network

  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    volumes:
      - ./backend/db/pgdata:/var/lib/postgresql/data
    networks:
      - meeting-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # audio-ml:
  #   build:
  #     context: ./ML
  #     dockerfile: Dockerfile
  #     args:
  #       HF_API_KEY: ${HF_API_KEY}
  #   ports:
  #     - "8053:8053"
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - HF_API_KEY=${HF_API_KEY}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   runtime: nvidia
  #   restart: unless-stopped
  #   networks:
  #     - meeting-network

networks:
  meeting-network:
    driver: bridge